name: Ping Render
on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render instance
        run: curl -X GET "https://n8n-self-hosted-1-6f9d.onrender.com/healthz"
